In [1]:
import numpy as np
import open3d as o3d
print(o3d.__version__)

# Animation callback function. it needs to contain as a minimum the visualizer reference
def rotate_around(vis):
    # We create a 3D rotation matrix from x,y,z rotations, the rotations need to be given in radians
    R = mesh.get_rotation_matrix_from_xyz((0, np.deg2rad(2), 0))
    # The rotation matrix is applied to the specified object - in our case the mesh. We can also specify the rotation pivot center
    mesh.rotate(R, center=(0, 0, 0))

    # We create a 3D rotation matrix for the sphere as well in the opposite direction
    R_sphere = mesh.get_rotation_matrix_from_xyz((0, np.deg2rad(-4), 0))
    # Apply it
    sphere_mesh.rotate(R_sphere, center=(0, 0, 0))
    # For the changes to be seen we need to update both the geometry that has been changed and to update the whole renderer connected to the visualizer
    vis.update_geometry(mesh)
    vis.update_geometry(sphere_mesh)
    vis.update_renderer()

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
0.16.0


In [2]:
# LOAD 
# Load mesh, together with setting the flag for post-processing to True, so the texture and material will be loaded
mesh_path = "AsteroidWall_Int.obj"
mesh = o3d.io.read_triangle_mesh(mesh_path,True)
# We can get information from the mesh like vertices, triangles, faces, UVs and texture
print(mesh)
print('Vertices:')
print(np.asarray(mesh.vertices))
print('Triangles:')
print(np.asarray(mesh.triangles))

TriangleMesh with 3932 points and 7866 triangles.
Vertices:
[[-2.26381397  4.15820217  0.73793399]
 [-2.23355603  4.10932112  0.73367399]
 [-2.263834    4.14955997  0.78367299]
 ...
 [ 0.57464498  3.85154295  0.46080899]
 [ 0.36781299  3.75395608  0.50451702]
 [ 0.328731    3.82142591  0.38308999]]
Triangles:
[[   0    1    2]
 [   3    4    5]
 [   6    7    8]
 ...
 [3214 3929 3921]
 [3929 1792 3204]
 [3925 1749 3929]]


In [3]:
if __name__ == '__main__':

    print(o3d.__version__)

    # Load mesh, together with setting the flag for post-processing to True, so the texture and material will be loaded
    mesh_path = 'AsteroidWall_Int.obj'
    mesh = o3d.io.read_triangle_mesh(mesh_path,True)

    print(mesh)
    print('Vertices:')
    print(np.asarray(mesh.vertices))
    print('Triangles:')
    print(np.asarray(mesh.triangles))


    # We can extract information from the mesh like faces, UVs and texture
    mesh_faces = mesh.triangles
    mesh_uvs = mesh.triangle_uvs
    texture = mesh.textures



    # We create a visualizer object that will contain references to the created window, the 3D objects and will listen to callbacks for key presses, animations, etc.
    vis = o3d.visualization.Visualizer()
    # New window, where we can set the name, the width and height, as well as the position on the screen
    vis.create_window(window_name='Angel Visualize', width=800, height=600)

    # We call add_geometry to add a mesh or point cloud to the visualizer
    vis.add_geometry(mesh)

    # We can easily create primitives like cubes, sphere, cylinders, etc. In our case we create a sphere and specify its radius
    sphere_mesh = o3d.geometry.TriangleMesh.create_sphere(radius=0.05)

    # We can compute either vertex or face normals
    sphere_mesh.compute_vertex_normals()
    # Add the sphere to the visualizer
    vis.add_geometry(sphere_mesh)
    # Translate it from the center
    sphere_mesh.translate((1, 0, 0))

    # We can register callback animation functions that will be run on every update cycle
    vis.register_animation_callback(rotate_around)
    # We run the visualizater
    vis.run()
    # Once the visualizer is closed destroy the window and clean up
    vis.destroy_window()

0.16.0
TriangleMesh with 3932 points and 7866 triangles.
Vertices:
[[-2.26381397  4.15820217  0.73793399]
 [-2.23355603  4.10932112  0.73367399]
 [-2.263834    4.14955997  0.78367299]
 ...
 [ 0.57464498  3.85154295  0.46080899]
 [ 0.36781299  3.75395608  0.50451702]
 [ 0.328731    3.82142591  0.38308999]]
Triangles:
[[   0    1    2]
 [   3    4    5]
 [   6    7    8]
 ...
 [3214 3929 3921]
 [3929 1792 3204]
 [3925 1749 3929]]
